package com.example.waggingtailsapplication.navigation

const val ROUT_SPLASH = "splash"
const val ROUT_HOME = "home"
const val ROUT_ABOUT = "about"
const val ROUT_WALKING = "walking"
const val ROUT_LOGIN = "login"
const val ROUT_SIGNUP = "signup"
const val ROUT_SERVICEDOG = "servicedog"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val ROUT_TRAINING = "training"
const val ROUT_SITTING = "sitting"
const val ROUT_ADMINLOGIN = "admin_login"
const val ROUT_ADMINSIGNUP = "admin_signup"